[package]
name = "merkle"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-msrv = "0.15.1"
sha3 = "0.10.8"
