[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-array = "1.0.0"
hex = "0.4.3"
hex-literal = "0.4.1"
sha2 = "0.10.8"
sha256 = "1.5.0"
